# This workflow will trigger a series of tests for our python functions

name: CI Test Python Functions

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && \
          apt-get install nano

      
    
